spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    static-path-pattern: /static/**
    async:
      request-timeout: 86400000
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  devtools:
    add-properties: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  jwt:
    secret: cMtNfCZTjYL6w9oDKNqwEkndAyiTK5FJAMZc
  smr:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJlbnRfaWQiOiJmMjc0YTVhYy01ZGYxLTZhMTItYjVhNy0zNzQ4YjI4NjkyNDYiLCJncm91cCI6IkthbnRhciBkZXYyIiwiY3VzdG9tIjoiMjMwMzAzX0NTQl81MjcwNDAwIiwiaWF0IjoxNjc3ODM1MzkxLCJleHAiOjE2ODMxMDU3OTF9.bcKiPrmCwHWELikvuc2Y3mtfEcj8aAJTMArNuheF_us
  main:
    allow-bean-definition-overriding: true

mail:
  userid: kantardev01@gmail.com
  passwd: mskvyfttzkatvhps

server:
  tomcat:
    max-swallow-size: -1

#Model Location
mybatis:
  type-aliases-package: com.kantar.vo
  check-config-location: true
  configuration:
    default-fetch-size: 100
    jdbc-type-for-null: null
  mapper-locations: classpath:sqlmap/*.xml
