srvinfo: prod

spring:
  datasource:
    hikari:
      max-lifetime: 9000
      idle-timeout: 8000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://52.78.44.197:3306/kantar?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: kantar_user
    password: zksxk!@12()90
  kafka:
    bootstrap-servers: 13.124.84.234:9092
    consumer:
      group-id: kantar
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#업로드 디렉토리는 협의 후 확정
file:
  upload-dir: classpath:/upload

#운영은 에러 로그 보이게 하기
logging:
  level:
    root: warn
    com:
      eura: debug
  file:
    path: classpath:/logs
    max-history: 7

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0
  auto:
    load:
      popular:
        drivers: false

domain: https://api.kantar.com
w3domain: https://kantar.com